# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Sangjun Cha
title: Graduate student (Ph.D candidate)
email: sang6199(at)yonsei.ac.kr
address: Department of Astronomy, Yonsei University, 637B Science Hall, 50 Yonsei-ro, Seodaemun-gu, Seoul, 03722, South Korea 
cv_url: "/assets/cv.pdf"

# Dark Mode (true/false/never)
darkmode: false

# Social links
orcid_url: https://orcid.org/0000-0001-7148-6915
orcid_icon_path: "/images/Orcid_icon.png"

google_scholar_url: https://scholar.google.com/citations?user=LBP1JiYAAAAJ&hl=en&oi=ao
google_scholar_icon_path: "/images/klipartz.com.png"

ads_url: https://ui.adsabs.harvard.edu/public-libraries/mftIqxqeSg2ElCDwWwv0jw
ads_icon_path: "/images/transparent_logo.svg"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/prof_pic.jpg 
about_content: | # this will include new lines to allow paragraphs
  I am a Ph.D. candidate in Astronomy at Yonsei University. I work on galaxy clusters using gravitational lensing. My research interests include modeling techniques for **gravitational lensing analysis, large-scale structures**, and **the study of massive galaxy clusters.**<br/> 
  I have developed lensing modeling algorithms such as **MARS (MAximum-entropy ReconStruction)** and **MrMARTIAN (Multi-resolution MAximum-entropy Reconstruction Technique Integrating Analytic Node)**, which leverage **automatic differentiation and optimizers provided by deep-learning frameworks (e.g., PyTorch)** to efficiently handle a large number of free parameters. I have also built a wide-field weak lensing mass reconstruction algorithm based on deep learning.<br/>
  My current interests include the **multiwavelength analysis of galaxy clusters**—using X-ray, radio, and intracluster light—to investigate the connection between baryonic and dark matter components, as well as the evolutionary history of galaxy clusters.<br/>

content:
  - title: Featured Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      <span style="font-size: 25px; font-weight:bold">A High-Caliber View of the Bullet Cluster Through JWST Strong and Weak Lensing Analyses</span><br/>
      <span style="font-size: 20px; font-style: italic">Published in</span> <span style="font-size: 20px; font-weight:bold">The Astrophysical Journal Letters</span>, <span style="font-size: 20px">[doi.org/10.3847/2041-8213/add2f0](https://iopscience.iop.org/article/10.3847/2041-8213/add2f0){:target="_blank"}</span><br/>
      <span style="font-size: 20px; font-style: italic">NASA press release</span>, <span style="font-size: 20px">[Link to the article](https://science.nasa.gov/missions/webb/nasa-webb-pierces-bullet-cluster-refines-its-mass/){:target="_blank"}</span><br/>
      <br/>
      ![JWST Bullet Cluster](/assets/Bullet_overlay.jpg){:style="float: left; margin: 0 1em 1em 0; max-width: 60%;"}<br/><br/><br/><br/>
      <span style="font-size: 17px">The Bullet Cluster is one of the most famous merging galaxy clusters. Using high-resolution JWST imaging, we have reconstructed its mass distribution by combining strong and weak gravitational lensing data. The left figure presents a multi-wavelength view of the Bullet Cluster. Our advanced JWST-based lensing analysis can offer new insights into the dynamics of galaxy cluster mergers and the nature of dark matter.</span>
      <div style="clear: both;"></div>
      <br/><br/>

      <span style="font-size: 25px; font-weight:bold">Precision MARS Mass Reconstruction of A2744: Synergizing the Largest Strong-lensing and Densest Weak-lensing Data Sets from JWST</span><br/>
      <span style="font-size: 20px; font-style: italic">Published in</span> <span style="font-size: 20px; font-weight:bold">The Astrophysical Journal</span>, <span style="font-size: 20px">[doi.org/10.3847/1538-4357/ad0cbf](https://iopscience.iop.org/article/10.3847/1538-4357/ad0cbf){:target="_blank"}</span><br/>
      <br/>
      ![JWST Abell 2744](/assets/A2744_JWST.jpeg){:style="float: right; margin: 0 0 1em 1.5em; max-width: 60%;"}<br/><br/><br/><br/>
      <span style="font-size: 17px">Abell 2744, also known as Pandora’s Cluster, is famous for its complex merging substructures. Using deep JWST observations of strong and weak gravitational lensing, we have reconstructed a high-resolution map of Abell 2744. The right figure shows mass contours from our analysis, revealing two mass bridges. With the orientation of observed radio relics, we propose the merger axes of Abell 2744.</span>
      <div style="clear: both;"></div>
      <br/>

  - title: Education
    layout: list
    content:
      - layout: top-left
        title: Yonsei University
        sub_title: B.S. in Astronomy & Physics 
        caption: 2015/03 - 2021/02
        
      - layout: top-left
        title: Yonsei University
        sub_title: Integrated course in Astronomy
        caption: 2021/03 - 2026/08 (expected)
        quote: >
          Supervisor: Prof. Myungkook. James Jee
          
  - title: Full Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      <span style="font-size: 25px; font-weight:bold">Publication Statistics</span>
      18 total refereed/under-reveiw papers. 
      **6 first-author papers** (5 refereed, 1 under review)
      **4 second or third author** and **8 co-author papers** (7 refereed, 5 under review)
      <br/><br/>
      
      <span style="font-size: 25px; font-weight:bold">First Author</span>
      <br/><br/>
      - <ins>MrMARTIAN: A Multi-resolution Mass Reconstruction Algorithm Combining Free-form and Analytic Components,</ins>, **Cha, S.**, Jee, M. J., 2025, [arXiv:2508.13262](https://arxiv.org/abs/2508.13262){:target="_blank"}, submitted to ApJ<br/><br/>
      - <ins>A High-Caliber View of the Bullet Cluster Through JWST Strong and Weak Lensing Analyses</ins>, **Cha, S.**, Cho, B. Y., Joo, H., Lee, W., HyeongHan, K., Scofield, Z. P., Finner, K., Jee, M. J., 2025, ApJL, 987, L15. [doi.org/10.3847/2041-8213/add2f0](https://iopscience.iop.org/article/10.3847/2041-8213/add2f0){:target="_blank"}<br/><br/>
      - <ins>Weak-lensing Mass Reconstruction of Galaxy Clusters with a Convolutional Neural Network. II. Application to Next-Generation Wide-Field Surveys</ins>, **Cha, S.**, Jee, M. J., Hong, S. E., Park, S., Bak, D., Kim, T., 2025, ApJ, 981, 52. [doi.org/10.3847/1538-4357/adb1b7](https://iopscience.iop.org/article/10.3847/1538-4357/adb1b7){:target="_blank"}<br/><br/>
      - <ins>Precision MARS Mass Reconstruction of A2744: Synergizing the Largest Strong-lensing and Densest Weak-lensing Data Sets from JWST</ins>, **Cha, S.**, HyeongHan, K., Scofield, Z. P., Joo, H., Jee, M. J., 2024, ApJ, 961, 186. [doi.org/10.3847/1538-4357/ad0cbf](https://iopscience.iop.org/article/10.3847/1538-4357/ad0cbf){:target="_blank"}<br/><br/>
      - <ins>Model-independent Mass Reconstruction of the Hubble Frontier Field Clusters with MARS Based on Self-consistent Strong-lensing data</ins>, **Cha, S.**, Jee, M. J., 2023, ApJ, 951, 140. [doi.org/10.3847/1538-4357/acd111](https://iopscience.iop.org/article/10.3847/1538-4357/acd111){:target="_blank"}<br/><br/>
      - <ins>MARS: A New Maximum-entropy-regularized Strong Lensing Mass Reconstruction Method</ins>, **Cha, S.**, Jee, M. J., 2022, ApJ, 931, 127. [doi.org/10.3847/1538-4357/ac69df](https://iopscience.iop.org/article/10.3847/1538-4357/ac69df){:target="_blank"}<br/><br/><br/><br/>
            
      <span style="font-size: 25px; font-weight:bold">Co-Author</span>
      <br/><br/>
      - <ins>Reproducing Abell 2744 with the HyperMillennium Simulation</ins>, Wang, Q., Li, M., Gao, L., Guo, Q., Angulo, R. E., **Cha, S.**, Cole, S., Frenk. C. S., HyeongHan, K., Li, R., Pei, W., Shan, H., Wang, J., White, S. D. M., 2025, [arXiv:2510.27291](https://arxiv.org/abs/2510.27291){:target="_blank"}, submitted to MNRAS<br/><br/>
      - <ins>Cosmology with supernova Encore in the strong lensing cluster MACS J0138-2155: Lens model comparison and H0 measurement</ins>, Suyu, S. H., Acebron, A., Grillo, C., Bergamini, P., Caminha, G. B., **Cha, S.**, Diego, J. M., Ertl, S., Foo, N., Frye, B. L., Fudamoto, Y., Granata, G., Halkola, A., Jee, M. J., Kamieneski, P. S., Koekemoer, A. M., Meena, A. K., Newman, A. B., Nishida, S., Oguri, M., Rosati, P., Schuldt, S., Zitrin, A., Cañameras, R., Hayes, E. E., Larison, C., Mamuzic, E., Millon, M., Pierel, J. D. R., Tortorelli, L., and Wang, H., 2025, [arXiv:2509.12319](https://arxiv.org/abs/2509.12319){:target="_blank"}, submitted to A&A<br/><br/>
      - <ins>Cosmology with supernova Encore in the strong lensing cluster MACS J0138-2155: Time delays & Hubble constant measurement</ins>, Pierel, J. D. R., Hayes, E. E., Millon, M., Larison, C., Mamuzic, E., Acebron, A., Agrawal, A., Bergamini, P., **Cha, S.**, Dhawan, S., Diego, J. M., Frye, B. L., Gilman, D., Granata, G., Grillo, C., Jee, M. J., Kamieneski, P. S., Koekemoer, A. M., Meena, A. K., Newman, A. B., Oguri, M., Padilla-Gonzalez, E., Poidevin, F., Rosati, P., Schuldt, S., Strolger, L. G., Suyu, S. H., Thorp, S., and Zitrin, A., 2025, [arXiv:2509.12301](https://arxiv.org/abs/2509.12301){:target="_blank"}, submitted to ApJ<br/><br/>
      - <ins>JWST Discovery of Strong Lensing from a Galaxy Cluster at Cosmic Noon: Giant Arcs and a Highly Concentrated Core of XLSSC 122</ins>, Finner, K., **Cha, S.**, Scofield, Z. P., Jee, M. J., Lin, Y.-. heng ., Joo, H., Park, H., Morishita, T., Faisst, A., Lee, B., Wang, W., Chary, R.-R., 2025, [arXiv:2508.08356](https://arxiv.org/abs/2508.08356){:target="_blank"}, submitted to ApJL<br/><br/>
      - <ins>Is Earendel a Star?: Investigating the Sunrise Arc Using JWST Strong and Weak Gravitational Lensing Analyses</ins>, Scofield, Z. P., Jee, M. J., **Cha, S.**, Park, H., 2025, [arXiv:2504.08879](https://arxiv.org/abs/2504.08879){:target="_blank"}, accepted to ApJ<br/><br/>
      - <ins>A dynamical mass measure of an inactive black hole in the distant universe</ins>, Newman, A. B., Gu, M., Belli, S., Ellis, R. S., Gangula, S., Greene, J. E., Walsh, J. L., Suyu, S. H., Ertl, S., Caminha, G., Granata, G., Grillo, C., Schuldt, S., Barone, T. M., Bird, S., Glazebrook, K., Jafariyazani, M., Kriek, M., Matthews, A., Morishita, T., Nanayakkara, T., Pierel, J. D. R., Acebron, A., Bergamini, P., **Cha, S.**, Diego, J. M., Foo, N., Frye, B., Fudamoto, Y., Jee, M. J., Kamieneski, P. S., Koekemoer, A. M., Meena, A. K., Nishida, S., Oguri, M., Rosati, P., Zitrin, A., 2025, [arXiv:2503.17478](https://arxiv.org/abs/2503.17478){:target="_blank"}, submitted<br/><br/>
      - <ins>Cosmology with Supernova Encore in the strong lensing cluster MACS J0138-2155: photometry, cluster members, and lens mass model</ins>, Ertl, S., Suyu, S. H., Schuldt, S., Granata, G., Grillo, C., Caminha, G. B., Acebron, A., Bergamini, P., Cañameras, R., **Cha, S.**, Diego, J. M., Foo, N., Frye, B. L., Fudamoto, Y., Halkola, A., Jee, M. J., Kamieneski, P. S., Koekemoer, A. M., Meena, A. K., Nishida, S., Oguri, M., Pierel, J. D. R., Rosati, P., Tortorelli, L., Wang, H., Zitrin, A., 2025, A&A, 702, A157 [doi.org/10.1051/0004-6361/202554477](https://www.aanda.org/articles/aa/full_html/2025/10/aa54477-25/aa54477-25.html){:target="_blank"}<br/><br/>
      - <ins>SN H0pe: The First Measurement of H<sub>0</sub> from a Multiply Imaged Type Ia Supernova, Discovered by JWST</ins>, Pascale, M., Frye, B. L., Pierel, J. D. R., Chen, W., Kelly, P. L., Cohen, S. H., Windhorst, R. A., Riess, A. G., Kamieneski, P. S., Diego, J. M., Meena, A. K., **Cha, S.**, Oguri, M., Zitrin, A., Jee, M. J., Foo, N., Leimbach, R., Koekemoer, A. M., Conselice, C. J., Dai, L., Goobar, A., Siebert, M. R., Strolger, L., Willner, S. P., 2025, ApJ, 979, 13. [doi.org/10.3847/1538-4357/ad9928](https://iopscience.iop.org/article/10.3847/1538-4357/ad9928){:target="_blank"}<br/><br/>
      - <ins>Weak-lensing detection of intracluster filaments in the Coma cluster</ins>, HyeongHan, K., Jee, M. J., **Cha, S.**, Cho, H., 2024, NatAs, 8, 377. [doi.org/10.1038/s41550-023-02164-w](https://www.nature.com/articles/s41550-023-02164-w){:target="_blank"}<br/><br/>
      - <ins>Weak-lensing Analysis of the Complex Cluster Merger A746 with Subaru/Hyper Suprime-Cam</ins>, HyeongHan, K., Cho, H., Jee, M. J., Wittman, D., **Cha, S.**, Lee, W., Finner, K., Rajpurohit, K., Brüggen, M., Forman, W., Jones, C., van Weeren, R., Botteon, A., Lovisari, L., Stroe, A., Domínguez-Fernández, P., O'Sullivan, E., Vrtilek, J., 2024, ApJ, 962, 100. [doi.org/10.3847/1538-4357/ad1bcc](https://iopscience.iop.org/article/10.3847/1538-4357/ad1bcc){:target="_blank"}<br/><br/>
      - <ins>Weak-lensing Mass Bias in Merging Galaxy Clusters</ins>, Lee, W., **Cha, S.**, Jee, M. J., Nagai, D., King, L., ZuHone, J., Chadayammuri, U., Felix, S., Finner, K., 2023, ApJ, 945, 71. [doi.org/10.3847/1538-4357/acb76b](https://iopscience.iop.org/article/10.3847/1538-4357/acb76b){:target="_blank"}<br/><br/>
      - <ins>Weak-lensing Mass Reconstruction of Galaxy Clusters with a Convolutional Neural Network</ins>, Hong, S. E., Park, S., Jee, M. J., Bak, D., **Cha, S.**, 2021, ApJ, 923, 266. [doi.org/10.3847/1538-4357/ac3090](https://iopscience.iop.org/article/10.3847/1538-4357/ac3090){:target="_blank"}<br/>

  - title: Talks
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **2025** Probing Dark Matter and Cluster Merger with JWST Strong and Weak Lensing: Case Studies of the Bullet Cluster and Abell 2744 / 33rd Texas Symposium on Relativistic Astrophysics / USA / Contributed (accepted)
      - **2025** Weak-lensing Detection and Reconstruction of Filamentary Structures in the Rubin Era: A Case Study of Abell 2744 / Korean Rubin Science Workshop 2025 / South Korea / Contributed
      - **2025** Lensing Analysis of Merging Clusters in the JWST Era: The Bullet Cluster and Abell 2744 / 2025 Merging Cluster Workshop / South Korea / Contributed
      - **2025** JWST Lensing Analysis of Merging Galaxy Clusters: The Bullet Cluster and Abell 2744 / CL2025: Entering a Golden Age of Galaxy Cluster Studies / Taiwan / Contributed
      - **2025** Probing Galaxy Cluster Mergers by Combining Strong and Weak Gravitational Lensing in the JWST Era / MPA / Germany
      - **2024** Probing Galaxy Clusters by Combining Strong and Weak Gravitational Lensing in the JWST Era / NOIRLab, University of Arizona / USA
      - **2024** Probing Galaxy Clusters by Combining Strong and Weak Lensing in the JWST Era: Mass Reconstruction of Abell 2744 / The 11th KIAS Workshop on Cosmology and Structure Formation / South Korea / Contributed
      - **2024** Do Globular Cluster Trace Dark Matter? / 2024 KAS Fall Meeting / South Korea / Contributed
      - **2024** Constraining Cosmological Parameters through Strong Lensing / 2024 KAS Spring Meeting / South Korea / Contributed
      - **2023** Precision MARS Mass Reconstruction of Abell 2744: Combining Large Strong and Weak Lensing Datasets from JWST / 2023 KAS Fall Meeting / South Korea / Contributed
      - **2022** Wide-field Weak-lensing Mass Reconstruction with Improved Convolutional Neural Network / 2022 KAS Fall Meeting / South Korea / Contributed
      - **2022** MARS Probe of Hubble Frontier Fields Clusters / IAUGA 2022 / South Korea / Contributed
      <br/>
      
  - title: Fellowship & Awards
    layout: text
    content: | # this will include new lines to allow paragraphs
      <span style="font-size: 18px; font-weight:bold">Integrated Undergraduate-and-Graduate Program Scholarship (Three-year full-tuition) </span><br/>
      <span style="font-size: 18px">Yonsei University </span><br/>
      2021 – 2023<br/><br/>
          
      <span style="font-size: 18px; font-weight:bold">Brain Korea 21 Plus Fellowship</span><br/>
      <span style="font-size: 18px">Yonsei University </span><br/>
      2021 – 2023<br/><br/>
      
      <span style="font-size: 18px; font-weight:bold">Yonsei Merit Academic Paper Award </span><br/>
      <span style="font-size: 18px">Yonsei University </span><br/>
      2023<br/><br/>

      <span style="font-size: 18px; font-weight:bold">Doctoral Student Research Fellowship (∼ $ 40,000) </span><br/>
      <span style="font-size: 18px">National Research Foundation of Korea </span><br/>
      2024 - 2026<br/><br/>

      <span style="font-size: 18px; font-weight:bold">Excellent Academic Paper Award </span><br/>
      <span style="font-size: 18px">Yonsei University </span><br/>
      2024<br/>

  - title: Military Service
    layout: text
    content: | # this will include new lines to allow paragraphs
      <span style="font-size: 18px; font-weight:bold"> Korea National Police Agency Auxiliary Police </span><br/>
      <span style="font-size: 18px"> Served as part of the mandatory military service in South Korea </span><br/>
      2016 – 2017<br/>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
